name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]

body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to file a bug report!

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear description of what the bug is
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction steps
      description: Steps to reproduce the behavior
      placeholder: |
        1. Create engine with...
        2. Execute query...
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What you expected to happen
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: RowQuery Version
      placeholder: "0.1.0"
    validations:
      required: true

  - type: input
    id: python-version
    attributes:
      label: Python Version
      placeholder: "3.12"
    validations:
      required: true

  - type: dropdown
    id: database
    attributes:
      label: Database Backend
      options:
        - SQLite
        - PostgreSQL
        - MySQL
        - Oracle
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Any other context about the problem
